

Nigel Farage could have strangled this story at birth. Confronted with the testimony of more than 20 former schoolmates, who shared with the Guardian their memories of a young Farage taunting Jews and other minorities in the most appalling terms – telling a Jewish pupil that “Hitler was right”, singing “Gas ’em all” and making a hissing sound to simulate lethal gas – he could have said: “I have no memory of what’s been described, but such behaviour would of course have been atrocious and if I was involved in any way, I am genuinely sorry.”
Sure, it would have been more of an “ifpology” than an apology, its admission of guilt wholly conditional, but it would surely have closed the story down. Reassured that the Reform UK leader had declared racist and antisemitic abuse unacceptable, most observers would have allowed that these events took place half a century ago and moved on.
But that is not what Farage did. Instead, he and his party have offered shifting accounts, moving from outright denial to non-denial denial and back again. That slipperiness itself raises questions about the character of the man who, according to the polls, is on course to be Britain’s next prime minister. But this episode also points to a larger and more alarming phenomenon, one that stretches far beyond these shores.
Farage’s defence rests on three pillars, each one of which is shaky. The first response has been to say the accusations are all untrue or, to put it another way, that his accusers are liars. As at least one of them has pointed out, that is itself an antisemitic trope: that Jews lie about their own suffering in pursuit of some devious, unstated end.
The second line of defence insists that Farage never did these things but, if he did, it would be irrelevant because he was only a child at the time. I’ve spoken to several Jewish community officials who say this is among the reasons why, so far, they have been reluctant to join the chorus of condemnation. True, the argument is undermined somewhat by the fact that Farage’s alleged conduct spanned a six-year period, right until he was a sixth former, aged 18, but it might just hold up – were it not for a flaw in Farage’s third defence.
This argues that the accusations against him lack force because they have no bearing on his politics today; that whatever the ex-pupils of Dulwich college might say about the boy of the 1970s and 1980s, the man of 2025 cannot be accused of antisemitism. Here the facts get a bit more awkward.
Consider one of Farage’s comments this week, in a broadcast interview where he gave that non-denial denial. “Have I said things 50 years ago that you could interpret as being banter in a playground, you could interpret in a modern light today in some sort of way? Yes.” Perhaps Farage was admitting there to less than his accusers recall, but it sounded as if he was suggesting that songs about gassing Jews, Asians and Black people amount to no more than “banter”. That’s not schoolboy Farage talking, but the Farage of 2025.
And that is far from the only mark against the fully adult politician. In 2017, the Board of Deputies of British Jews said he had “crossed the line into well-known antisemitic tropes”, after he had nodded along while a caller to his LBC show claimed that Israel had both the Republican and Democratic parties “in their pockets”. Farage replied: “In terms of money and influence they are a very powerful lobby”, explaining that “there are about six million Jewish people living in America, so as a percentage it’s quite small, but in terms of influence it’s quite big”.
Three years later, the Board of Deputies again denounced the then Brexit party leader for trading “in dog whistles and tropes”, after he had repeatedly deployed words and motifs that are staples of far-right antisemitic conspiracy theory.
In that period, Farage was ticking off almost every item on the trope bingo card, railing against “globalists”, “cultural Marxists”, Goldman Sachs and George Soros, the latter a perennial hate figure to those who allege a secret Jewish plot to undermine nation states in pursuit of global government. In a 2020 article for Newsweek, Farage aimed his fire at “unelected globalists shaping the public’s lives based on secret recommendations from the big banks”.
The Community Security Trust, or CST, the organisation that monitors and combats antisemitism in the UK, lambasted Farage at the time for using “language that evokes antisemitic conspiracy codewords”, warning that “this search for scapegoats will keep requiring new enemies and new excuses, moving the national debate into more polarising and dangerous places”.
There was particular disquiet at the company Farage was keeping, cheerfully sitting alongside the notorious Alex Jones of Infowars, for example, as the pair played some of the greatest hits of antisemitic conspiracy theory, from the Bilderberg group to “new world order”. Farage was no less happy to be interviewed at least six times by Rick Wiles, a far-right US pastor who would later brand the impeachment of Donald Trump a “Jew coup”.
Which brings us to that larger phenomenon. Talk to the CST today and it is clear that the most urgent, direct threat to Jewish safety is violent jihadism, of the kind that saw Jihad al-Shamie launch a deadly attack on Heaton Park synagogue in Manchester last month. But what it sees as a growing long-term danger is a shift now under way on the US right.
The fear, as CST policy director Dave Rich puts it, is that “Nick Fuentes becomes the face of the Republican movement” – Fuentes being the unabashed white supremacist and Holocaust denier who once dined with Trump at Mar-a-Lago and who, some warn, is poised to replace Charlie Kirk as the darling of the next Republican generation.
Dispensing with the previous posture in which rightwing politicians deflected accusations of antisemitism by boasting of their pro-Israel credentials – even if their support for Israel amounted to no more than taking sides in what they saw as a battle of the west against Islam – Fuentes, Tucker Carlson and others are moving into a new place. No longer speaking of “Judeo-Christian values”, but espousing instead an aggressive Christian nationalism, they are increasingly hostile to Israel and Zionism, and seemingly motivated not by sympathy for the Palestinians, but rather by an updated version of the 1930s, America First view that suspected a Jewish plot to drag America to war. Given the global might of the US, such a change to the American right would have a profound effect on Jews the world over.
All of which is a long way from the playground of Dulwich college. But perhaps it explains why Nigel Farage’s youth is not quite as irrelevant as he would have us believe. Because the past has a nasty habit of intruding into the present – and future.


নাইজেল ফারাজ এই গল্পটিকে জন্ম মুহূর্তেই দমিয়ে দিতে পারতেন। প্রায় ২০ জনেরও বেশি সাবেক সহপাঠীর সাক্ষ্য—যারা গার্ডিয়ানকে বলেছেন যে তরুণ ফারাজ ইহুদি এবং অন্যান্য সংখ্যালঘুদের সবচেয়ে জঘন্য ভাষায় উপহাস করত, এক ইহুদি ছাত্রকে বলত “হিটলার ঠিকই করেছিল”, “গ্যাস ’এম অল” গান গাইত এবং মারাত্মক গ্যাসের শব্দ নকল করতে হিসহিস করত—এর মুখোমুখি হয়ে তিনি বলতে পারতেন: “আমি যা বলা হচ্ছে তার কিছুই মনে করতে পারছি না, তবে এমন আচরণ অবশ্যই ভয়াবহ, এবং যদি আমি কোনোভাবে এতে জড়িত থাকি, তবে আমি সত্যিই দুঃখিত।”
নিঃসন্দেহে, এটি পুরোপুরি ক্ষমা নয়—বরং “যদি” ভিত্তিক ক্ষমা—তবুও এটি সম্ভবত ঘটনাটিকে শেষ করত। রিফর্ম ইউকে দলের নেতা জাতিগত বা ইহুদিবিদ্বেষী গালিগালাজকে অগ্রহণযোগ্য বলে ঘোষণা করেছেন জেনে অধিকাংশ পর্যবেক্ষক স্বীকার করতেন যে ঘটনাগুলো আধা শতাব্দী পুরোনো, এবং সেখানেই বিষয় শেষ হয়ে যেত।
কিন্তু ফারাজ তা করেননি। বরং তিনি এবং তাঁর দল পাল্টে পাল্টে বিভিন্ন ব্যাখ্যা দিয়েছেন—সম্মুখ থেকে অস্বীকার, তারপর আধা-অস্বীকার, তারপর আবার অস্বীকারে ফেরা। এই পিচ্ছিল মনোভাবই প্রশ্ন তোলে সেই ব্যক্তির চরিত্র নিয়ে, যিনি জরিপ অনুযায়ী ব্রিটেনের পরবর্তী প্রধানমন্ত্রী হওয়ার পথে রয়েছেন। কিন্তু এই ঘটনাটি আরও বৃহৎ এবং উদ্বেগজনক এক প্রবণতার দিকে ইঙ্গিত করে, যা ব্রিটেনের বাইরেও বিস্তৃত।
ফারাজের প্রতিরক্ষা তিনটি স্তম্ভের ওপর দাঁড়ানো, যার প্রতিটিই দুর্বল। প্রথম প্রতিক্রিয়া হলো অভিযোগগুলো মিথ্যা বলা, অর্থাৎ তাঁর অভিযোগকারীরা মিথ্যাবাদী। এদের মধ্যে অন্তত একজন উল্লেখ করেছেন যে নিজেই এই অভিযোগ একটি ইহুদিবিদ্বেষী ধারণা—যে ইহুদিরা নিজেদের ভোগান্তি নিয়ে মিথ্যা বলে কোনো গোপন উদ্দেশ্য সাধনের জন্য।
দ্বিতীয় প্রতিরক্ষা হলো, ফারাজ এসব কখনো করেননি; আর করেও থাকলে তা গৌণ, কারণ তিনি তখন শিশু ছিলেন। কয়েকজন ইহুদি সম্প্রদায়ের কর্মকর্তার সঙ্গে আমার কথা হয়েছে, তাঁরা বলেছেন এটাই কারণ যে তাঁরা এখনো প্রকাশ্যে নিন্দায় যোগ দেননি। সত্য, এই যুক্তিটা দুর্বল হয়ে যায় কারণ ফারাজের অভিযোগিত আচরণ ছয় বছর ধরে চলেছিল, যখন তিনি ষষ্ঠ-ফর্মে ১৮ বছর বয়সী ছিলেন। তবুও এই যুক্তি টিকতে পারত—যদি না তাঁর তৃতীয় প্রতিরক্ষায় বড় ত্রুটি থাকত।
তৃতীয় যুক্তি হলো, এসব অভিযোগ আজকের তাঁর রাজনীতির সঙ্গে সম্পর্কহীন, তাই অকার্যকর; ৭০–৮০ দশকের ডুলউইচ কলেজের ছাত্র সম্পর্কে যা-ই বলা হোক, ২০২৫ সালের মানুষটিকে ইহুদিবিদ্বেষী বলা যায় না। এখানে বিষয়টি একটু জটিল হয়ে পড়ে।
উদাহরণস্বরূপ, এই সপ্তাহে এক সাক্ষাৎকারে ফারাজ আধা-অস্বীকার করতে গিয়ে বলেছেন: “৫০ বছর আগে আমি এমন কিছু বলে থাকতে পারি, যা আপনি হয়ত খেলার ছলে বলা ‘বান্টার’ হিসেবে ব্যাখ্যা করবেন—আজকের চোখে এগুলো ভিন্নভাবে দেখা যাবে। হ্যাঁ।” এটি হয়তো তাঁর বিরুদ্ধে আনা অভিযোগের চেয়ে কম কিছু স্বীকার করা, তবে শোনাতে এমন লাগে যেন তিনি বলছেন—ইহুদি, এশিয়ান বা কৃষ্ণাঙ্গদের ‘গ্যাসে মারা’ নিয়ে গান করা ছিল নিছক ‘মজা’। এটি স্কুলের ছেলের কথা নয়—এটি ২০২৫ সালের ফারাজের কথা।
এবং এটাই তাঁর পূর্ণবয়স্ক রাজনৈতিক চরিত্রের একমাত্র দাগ নয়। ২০১৭ সালে, ব্রিটিশ জুইশ ডেপুটিস বোর্ড বলেছিল তিনি “পরিচিত ইহুদিবিদ্বেষী ধারণার সীমা অতিক্রম করেছেন”, কারণ তিনি তাঁর এলবিসি শো-তে এক কলারের সেই বক্তব্যে সায় দিয়েছিলেন যে ইসরায়েল নাকি রিপাবলিকান এবং ডেমোক্র্যাট—উভয় দলকেই “নিজের পকেটে” রেখেছে। ফারাজ বলেছিলেন: “টাকা এবং প্রভাবের দিক থেকে তারা খুব শক্তিশালী লবি”, ব্যাখ্যা করে বলেন, “আমেরিকায় প্রায় ৬ মিলিয়ন ইহুদি আছে, শতাংশ কম হলেও প্রভাব অনেক বেশি।”
তিন বছর পর, বোর্ড আবারো তাঁকে নিন্দা করে বলেছিল যে তিনি “ডগ হুইসল এবং ট্রোপ” ব্যবহার করছেন—ডানপন্থী ইহুদিবিদ্বেষী ষড়যন্ত্রের ভাষা ও প্রতীক।
এই সময়ে, ফারাজ প্রায় সব পরিচিত ষড়যন্ত্র-বিষয়ক কথাবার্তাই ব্যবহার করছিলেন—“গ্লোবালিস্ট”, “কালচারাল মার্ক্সিস্ট”, গোল্ডম্যান স্যাক্স, জর্জ সোরোস—যিনি সবসময়ই সেইসব ষড়যন্ত্রীদের লক্ষ্য, যারা দাবি করে ইহুদিরা গোপনে জাতিগুলোকে ধ্বংস করে “গ্লোবাল গভর্নমেন্ট” স্থাপনের ষড়যন্ত্র করছে। ২০২০ সালে নিউজউইকের এক প্রবন্ধে ফারাজ আক্রমণ করেন “অবাঞ্ছিত গ্লোবালিস্টদের”, যারা “বড় ব্যাংকের গোপন সুপারিশ” অনুযায়ী জনগণের জীবন নিয়ন্ত্রণ করছে।
সিএসটি—যুক্তরাজ্যের ইহুদিবিদ্বেষ পর্যবেক্ষণকারী সংস্থা—তখন তাঁকে সমালোচনা করে বলেছিল তিনি “অ্যান্টিসেমিটিক কোডওয়ার্ডের মতো ভাষা ব্যবহার” করছেন এবং সতর্ক করেছিল যে “এই স্কেপগোট খোঁজার প্রবণতা নতুন শত্রু সৃষ্টি করবে এবং সমাজকে আরও বিপজ্জনক দিকে ঠেলে দেবে।”
বিশেষ উদ্বেগ ছিল ফারাজের সঙ্গ—যেমন berখ্যাত অ্যালেক্স জোন্সের (ইনফোওয়ার্স) পাশে হাসিমুখে বসে বিভিন্ন ইহুদিবিদ্বেষী ষড়যন্ত্র আলোচনা করা—বিল্ডারবার্গ গ্রুপ থেকে “নিউ ওয়ার্ল্ড অর্ডার” পর্যন্ত। একইভাবে, তিনি একাধিকবার সাক্ষাৎ দিয়েছেন রিক উইলসের কাছে—যিনি পরে ট্রাম্পের অভিশংসনকে “জিউ কূপ” বলেছিলেন।
এখান থেকেই বৃহত্তর চিত্রটি স্পষ্ট হয়। সিএসটির মতে, ইহুদিদের জন্য এখন সবচেয়ে প্রত্যক্ষ হুমকি হলো সহিংস জিহাদবাদ, যেমন গত মাসে ম্যানচেস্টারের হিটন পার্ক সিনাগগে জিহাদ আল-শামির হামলা। কিন্তু দীর্ঘমেয়াদে আরও বড় বিপদ আসছে মার্কিন ডানপন্থার পরিবর্তন থেকে।
সিএসটির নীতিনির্দেশক ডেভ রিচের ভাষায়, আশঙ্কা হলো “নিক ফুয়েন্তেস যেন রিপাবলিকান আন্দোলনের মুখ না হয়ে ওঠে”—যে ব্যক্তি নির্লজ্জ শ্বেত-সর্বোচ্চতাবাদী এবং হলোকাস্ট অস্বীকারকারী, যিনি ট্রাম্পের সঙ্গে নৈশভোজ করেছিলেন এবং যাকে অনেকেই আশঙ্কা করছেন রিপাবলিকান যুব প্রজন্মের নতুন নায়ক হিসেবে।
আগের মতো “ইসরায়েল-সমর্থন” দেখিয়ে নিজেদের ইহুদিবিদ্বেষহীন বলতে চাইছে না মার্কিন ডানপন্থীরা। ফুয়েন্তেস, টাকার কার্লসন প্রমুখ এখন আগ্রাসী খ্রিষ্টান জাতীয়তাবাদ প্রচার করছেন, ইসরায়েল এবং জায়নিজমের প্রতি ক্রমশই শত্রুভাবাপন্ন। তাঁদের উদ্দেশ্য ফিলিস্তিনিদের প্রতি সহানুভূতি নয়—বরং ১৯৩০-এর দশকের আমেরিকা ফার্স্ট মতাদর্শের আধুনিক সংস্করণ, যা মনে করত ইহুদিরা আমেরিকাকে যুদ্ধে টেনে নিতে চাইছে। যুক্তরাষ্ট্রের বিশ্বব্যাপী প্রভাব বিবেচনায়, মার্কিন ডানপন্থার এমন দিক পরিবর্তন পৃথিবীর সর্বত্র ইহুদিদের ওপর গভীর প্রভাব ফেলতে পারে।
সব মিলিয়ে, এটা ডুলউইচ কলেজের মাঠ থেকে অনেক দূরের বিষয়। কিন্তু হয়তো এ কারণেই ফারাজের শৈশব ততটা অপ্রাসঙ্গিক নয়, যতটা তিনি আমাদের বিশ্বাস করাতে চান। অতীতের একটি দুষ্ট স্বভাব রয়েছে—এটি বারবার বর্তমান ও ভবিষ্যতে ফিরে আসে।

